title = "Ryan Wigley"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Ryan Wigley"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "ryan-website-favicon.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/rywigs"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/rywigs/"
